"""
Run `searching.evaluate` over the word corpora in test/subwords/.

Corpora
-------
Each file holds one word per line, in Python list notation.

    known_valid.txt         hand-curated; every word must evaluate True
    known_non_valid.txt     hand-curated; every word must evaluate False
    braid_orbit_*.txt       generated by braid_orbit.py from the braid action, so every
                            word is drawable by construction -- any False is a real bug
    mostly_non_valid.txt    a large mixed set with no per-line ground truth; reported as
                            a tally only, useful for spotting a change in behaviour

Run it directly, or via `run_tests()` in a `python3 -i main.py` session.
"""

# Make the modules in the repository root importable from inside test/.
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

import ast

from searching import evaluate

SUBWORDS = Path(__file__).resolve().parent / "subwords"

# filename -> the result every word in it must give, or None where there is no
# per-line ground truth and only a tally is reported.
CORPORA = {
    "known_valid.txt": True,
    "known_non_valid.txt": False,
    "braid_orbit_braidlength7_rank7.txt": True,
    "mostly_non_valid.txt": None,
}

# Large enough for every corpus.  Extra punctures are neither a help nor a hindrance,
# so one rank serves all the files (see searching.evaluate).
RANK = 15


def evaluate_from_file(path: Path, rank: int = RANK) -> tuple[int, int]:
    """Return (true_count, false_count) for the words in one corpus file."""
    true_count = 0
    false_count = 0
    with open(path) as f:
        for line in f:
            word = ast.literal_eval(line.strip())
            if evaluate(rank, word):
                true_count += 1
            else:
                false_count += 1
    return true_count, false_count


def report(filename: str, expected: bool | None) -> int:
    """Evaluate one corpus and print its tally.  Returns the number of failures."""
    true_count, false_count = evaluate_from_file(SUBWORDS / filename)
    total = true_count + false_count
    failures = 0 if expected is None else (false_count if expected else true_count)

    if expected is None:
        status = "--"
    else:
        status = "ok" if failures == 0 else "FAIL"

    print(f"  [{status}] {filename}")
    print(f"         True: {true_count}/{total}    False: {false_count}/{total}", end="")
    print(f"    (expected all {expected})" if expected is not None else "    (no ground truth)")
    return failures


def main() -> int:
    """Run every corpus.  Returns 1 if any word contradicted its expected result."""
    print("------------------------------")
    print(f"corpora: {len(CORPORA)} files, rank {RANK}")

    failures = sum(report(filename, expected) for filename, expected in CORPORA.items())

    print("------------------------------")
    print("ALL PASS" if failures == 0 else f"{failures} FAILURES")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
